spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board
    username: root
    password: 1111
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-authentication-method: client_secret_post
            client-id: 7b3364f15ae2b0056f2c11be37baaed6 # ??? ??
            client-secret: crLXkzEaewiCWZfoPWSnj6lA1mqsRYzN # ??? ??
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao" # ??? ??
            client-name: Kakao
            scope:
              - profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jwt:
    secret: askdjalksdjlkasdjlkasjdlkasdlkajsdlkasasdasdasdasdjdlkasjdlasdas
# ??? api? 	7b3364f15ae2b0056f2c11be37baaed6
# ????? ???? 	crLXkzEaewiCWZfoPWSnj6lA1mqsRYzN
